apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /host-data/perfstack
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data
  namespace: perfstack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: backend-data-pv
  resources:
    requests:
      storage: 1Gi
