apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: perfstack
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:2.7
          ports:
            - containerPort: 8086
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: "setup"
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: "admin"
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              value: "admin12345"
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: "perfstack"
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: "k6"
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              value: "perfstack-token"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: perfstack
spec:
  selector:
    app: influxdb
  ports:
    - port: 8086
      targetPort: 8086
